feat: add a new plugin newyork_times
TaskingAI/TaskingAI pull request #218
Opened 2024-06-24 10:02 UTC by LinkW77

# Pull Request

## PR Description

Add a new plugin New York Times with Search API and Top Stories API

## Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Performance enhancement
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other, please describe:

## Checklist

Before submitting this PR, please make sure:

- [x] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) guidelines.
- [x] I have tested my changes locally to ensure they are effective.
- [x] I have updated the necessary documentation (if applicable).

2024-06-25 06:46 UTC, DynamesC requested changes

2024-06-25 06:46 UTC, DynamesC commented on plugin/bundles/nytimes/plugins/news_search/plugin.py
Add input format validation. If begin_date or end_date does not meet with the required format, raise request validation error.

2024-06-25 06:46 UTC, DynamesC commented on plugin/bundles/nytimes/resources/i18n/en.yml
Update description for start and end date for better clarity.

My personal opinion:

Start Date: The earliest publication date for articles returned by the search. Articles published before this date are not included in the results.
End Date: The latest publication date for articles returned by the search. Articles published after this date are not included in the results.

2024-07-01 03:15 UTC, DynamesC approved these changes
LGTM

2024-07-01 06:41 UTC, taskingaijc approved these changes
LGTM

2024-07-12 05:46 UTC, merged