feat: add a new plugin stack_overflow
TaskingAI/TaskingAI pull request #219
Opened 2024-06-24 10:04 UTC by LinkW77

# Pull Request

## PR Description

Add a new plugin Stack Overflow to solve programming questions

## Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Performance enhancement
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other, please describe:

## Checklist

Before submitting this PR, please make sure:

- [x] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) guidelines.
- [x] I have tested my changes locally to ensure they are effective.
- [x] I have updated the necessary documentation (if applicable).

2024-06-25 06:21 UTC, DynamesC commented on plugin/bundles/stack_overflow/resources/i18n/en.yml
rename input 'not_tagged''s name to human reading format, for example 'Not Tagged'. And also update its description to explain more

2024-06-25 06:21 UTC, DynamesC commented on plugin/bundles/stack_overflow/resources/bundle_schema.yml
provider should be: StackOverflow

2024-07-01 06:44 UTC, taskingaijc approved these changes
LGTM

2024-07-12 05:36 UTC, DynamesC approved these changes
LGTM

2024-07-12 05:45 UTC, DynamesC requested changes

2024-07-12 05:45 UTC, DynamesC commented on plugin/bundles/stack_overflow/plugins/stack_overflow_search/plugin.py
> +        url = f"https://api.stackexchange.com/2.3/search?site=stackoverflow&tagged={tagged}&nottagged={not_tagged}&intitle={title}&sort={sort}&order={order}"
Only append parameters when the parameter is presented

2024-07-12 08:13 UTC, DynamesC approved these changes
LGTM

2024-07-12 08:18 UTC, taskingaijc approved these changes
LGTM

2024-07-12 08:19 UTC, merged