feat: add a new plugin finance news
TaskingAI/TaskingAI pull request #288
Opened 2024-07-19 07:59 UTC by LinkW77

# Pull Request

## PR Description

Add a new plugin finance news

## Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Performance enhancement
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other, please describe:

## Checklist

Before submitting this PR, please make sure:

- [x] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) guidelines.
- [x] I have tested my changes locally to ensure they are effective.
- [x] I have updated the necessary documentation (if applicable).

2024-07-24 10:32 UTC, DynamesC requested changes

2024-07-24 10:32 UTC, DynamesC commented on plugin/bundles/finance_news/plugins/finance_news_search/plugin.py
> +        finance_news_api_key: str = credentials.credentials.get("FINANCE_NEWS_API_KEY")
check input data formats before using them

2024-07-24 10:32 UTC, DynamesC commented on plugin/bundles/finance_news/resources/i18n/en.yml
> +finance_news_search_input_date_description: "Use this parameter to specify a date or date range. Example: &date=2020-01-01 for news on Jan 1st and &date=2020-12-24,2020-12-31 for news between Dec 24t
1. remove '&date='
2. Make descriptions starting from 'Available options' more readable.

2024-07-24 10:32 UTC, DynamesC commented on plugin/bundles/finance_news/resources/i18n/en.yml
> +finance_news_search_input_source_description: "Use this parameter to include or exclude one or multiple comma-separated news sources. Example: To include forbes.com, but exclude bloomberg.com: &sourc
remove '&sources'

2024-07-24 10:32 UTC, DynamesC commented on plugin/bundles/finance_news/resources/i18n/en.yml
> +finance_news_search_input_tags_description: "Use this parameter to search for tags by which news are tagged. You can search by multiple tags, separating tags with a comma, you can also exclude tags t
remove '&tags'

2024-08-19 11:59 UTC, DynamesC approved these changes
LGTM

2024-08-22 08:27 UTC, jameszyao approved these changes
LGTM

2024-08-22 08:27 UTC, merged